# Generated by Django 4.1.7 on 2023-03-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetmodel',
            old_name='filesize',
            new_name='file_size',
        ),
    ]
